version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    depends_on:
      - db

  db:
    image: "tiangolo/uwsgi-nginx-flask:python3.10"
    volumes:
      - ./database:/app/database
